# Generated by Django 5.0.6 on 2024-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('A', 'Arms'), ('B', 'Back'), ('C', 'Chest'), ('F', 'Full Body'), ('L', 'Legs'), ('S', 'Shoulders')], default='F', max_length=1)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
