# Generated by Django 5.0.6 on 2024-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_exercise_equipment_exercise_weight_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
